name: Backend build & Push

on:
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: app/backend
        
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v5
        with:
         aws-access-id: ${{secrets.AWS_Access_Key_Id}}
         aws-secret-access_key: ${{secrets.AWS_Secret_Access_Key}}
         aws-region: us-east-1

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker Build & Push
        uses: docker/build-push-action@v3
        with:
          context: app/backend
          path: app/backend/Dockerfile
          tags: 804867352391.dkr.ecr.us-east-1.amazonaws.com/dev/backend:${{github.run_number}}
